config/routes.rb
Rails.application.routes.draw do
  resources :wine_strains
  resources :strains
  resources :wines
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains
    has_many :strains, through: :wine_strains
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name)
    end
end

app/controllers/wine_strains_controller.rb
class WineStrainsController < ApplicationController
  before_action :set_wine_strain, only: %i[ show edit update destroy ]

  # GET /wine_strains or /wine_strains.json
  def index
    @wine_strains = WineStrain.all
  end

  # GET /wine_strains/1 or /wine_strains/1.json
  def show
  end

  # GET /wine_strains/new
  def new
    @wine_strain = WineStrain.new
  end

  # GET /wine_strains/1/edit
  def edit
  end

  # POST /wine_strains or /wine_strains.json
  def create
    @wine_strain = WineStrain.new(wine_strain_params)

    respond_to do |format|
      if @wine_strain.save
        format.html { redirect_to wine_strain_url(@wine_strain), notice: "Wine strain was successfully created." }
        format.json { render :show, status: :created, location: @wine_strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wine_strains/1 or /wine_strains/1.json
  def update
    respond_to do |format|
      if @wine_strain.update(wine_strain_params)
        format.html { redirect_to wine_strain_url(@wine_strain), notice: "Wine strain was successfully updated." }
        format.json { render :show, status: :ok, location: @wine_strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wine_strains/1 or /wine_strains/1.json
  def destroy
    @wine_strain.destroy

    respond_to do |format|
      format.html { redirect_to wine_strains_url, notice: "Wine strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine_strain
      @wine_strain = WineStrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_strain_params
      params.require(:wine_strain).permit(:wine_id, :strain_id, :Percentage)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, {strain_ids: []} )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wine_strains_helper.rb
module WineStrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cepas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/strains/_form.html.erb
<%= form_with(model: strain) do |form| %>
  <% if strain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
        <% strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/_strain.html.erb
<div id="<%= dom_id strain %>">
  <p>
    <strong>Name:</strong>
    <%= strain.name %>
  </p>

</div>

app/views/strains/edit.html.erb
<h1>Editing strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Show this strain", @strain %> |
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Strains</h1>

<div id="strains">
  <% @strains.each do |strain| %>
    <%= render strain %>
    <p>
      <%= link_to "Show this strain", strain %>
    </p>
  <% end %>
</div>

<%= link_to "New strain", new_strain_path %>

app/views/strains/new.html.erb
<h1>New strain</h1>

<%= render "form", strain: @strain %>

<br>

<div>
  <%= link_to "Back to strains", strains_path %>
</div>

app/views/strains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @strain %>

<div>
  <%= link_to "Edit this strain", edit_strain_path(@strain) %> |
  <%= link_to "Back to strains", strains_path %>

  <%= button_to "Destroy this strain", @strain, method: :delete %>
</div>

app/views/wine_strains/_form.html.erb
<%= form_with(model: wine_strain) do |form| %>
  <% if wine_strain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wine_strain.errors.count, "error") %> prohibited this wine_strain from being saved:</h2>

      <ul>
        <% wine_strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :wine_id, style: "display: block" %>
    <%= form.text_field :wine_id %>
  </div>

  <div>
    <%= form.label :strain_id, style: "display: block" %>
    <%= form.text_field :strain_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wine_strains/_wine_strain.html.erb
<div id="<%= dom_id wine_strain %>">
  <p>
    <strong>Wine:</strong>
    <%= wine_strain.wine_id %>
  </p>

  <p>
    <strong>Strain:</strong>
    <%= wine_strain.strain_id %>
  </p>

</div>

app/views/wine_strains/edit.html.erb
<h1>Editing wine strain</h1>

<%= render "form", wine_strain: @wine_strain %>

<br>

<div>
  <%= link_to "Show this wine strain", @wine_strain %> |
  <%= link_to "Back to wine strains", wine_strains_path %>
</div>

app/views/wine_strains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wine strains</h1>

<div id="wine_strains">
  <% @wine_strains.each do |wine_strain| %>
    <%= render wine_strain %>
    <p>
      <%= link_to "Show this wine strain", wine_strain %>
    </p>
  <% end %>
</div>

<%= link_to "New wine strain", new_wine_strain_path %>

app/views/wine_strains/new.html.erb
<h1>New wine strain</h1>

<%= render "form", wine_strain: @wine_strain %>

<br>

<div>
  <%= link_to "Back to wine strains", wine_strains_path %>
</div>

app/views/wine_strains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wine_strain %>

<div>
  <%= link_to "Edit this wine strain", edit_wine_strain_path(@wine_strain) %> |
  <%= link_to "Back to wine strains", wine_strains_path %>

  <%= button_to "Destroy this wine strain", @wine_strain, method: :delete %>
</div>

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div class="field">
      <%= form.label :strains %>
          <%= form.collection_check_boxes(:strain_ids,
                                          Strain.all,
                                              :id,
                                              :name) do |b| %>
          <%= b.label class:"label-checkbox" do%>
              <%=b.check_box + b.text%>
          <%end%>
      <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine.html.erb
<div id="<%= dom_id wine %>">
  <p>
    <strong>Name:</strong>
    <%= wine.name %>
  </p>

</div>

app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to "Show this wine", @wine %> |
  <%= link_to "Back to wines", wines_path %>
</div>

app/views/wines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wines</h1>

<div id="wines">

   <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Score</th>
                <th>Strains</th>
                <th>Tag quantity</th>
                <th>Tags</th>
                <th colspan="3"></th>
            </tr>
        </thead>
    <tbody>
      <% @wines.each do |wine| %>         
        <tr>
            <td><%= wine.name %></td>
            <td><%= wine.score %></td>
            <td><%= wine.strains.map(&:name).join(',') %></td>

            <td><%= link_to 'Show', wine %></td>
            <td><%= link_to "Editar", edit_wine_path(wine) %></td>
            <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
     </tbody>
    </table>

<%= link_to "Nuevo vino", new_wine_path %>

app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to "Back to wines", wines_path %>
</div>

app/views/wines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wine %>

<div>
  <%= link_to "Edit this wine", edit_wine_path(@wine) %> |
  <%= link_to "Back to wines", wines_path %>

  <%= button_to "Destroy this wine", @wine, method: :delete %>
</div>